# for prod environment
spring:
  boot:
    admin:
      url: http://spring-boot-admin
      username: mobvoi
      password: mobvoi
  gson:
    converter:
      enable: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    debug: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://tidb-growth-cluster:4000/wwstore_log?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: mobvoi
    password: mobvoiawesome
  swagger:
    enable: true
  zipkin:
    base-url: http://zipkin.tiktime.net
  sleuth:
    sampler:
      percentage: 1
endpoints:
  sensitive: false
fourPX:
  host: http://apisandbox.4px.com/api/service
  customerId: 100800
  token: oDuCfVi88b40oOuMYQUOcTh2b/T+uJdDBsJ+VOrlG6Q=1
