logging:
  level:
    org.springframework.cloud.config.client: WARN
    org.springframework.boot.autoconfigure.security: WARN

endpoints:
  health:
    sensitive: true
  metrics:
    sensitive: true

from: config-client-default